version: '3'
services:
  hotel-nginx:
    container_name: hotel-nginx
    build:
      context: docker/nginx
    volumes:
      - ./:/var/www
    depends_on:
      - hotel-php-fpm
    ports:
      - "8000:80"
    networks:
      - internal

  hotel-php-fpm:
    container_name: hotel-php-fpm
    build:
      context: docker/php-fpm
    volumes:
      - ./:/var/www
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.110.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - hotel-postgres
      - mailer
      - hotel-redis
    networks:
      - internal

  hotel-node:
    image: node:12.7-alpine
    volumes:
      - ./app:/app
    working_dir: /app
    networks:
      - internal

  hotel-postgres:
    container_name: hotel-postgres
    image: postgres:11.2-alpine
    volumes:
      - hotel-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "secret"
      POSTGRES_USER: "symfony"
      POSTGRES_DB: "app"
    ports:
      - "54321:5432"
    networks:
      - internal

  hotel-redis:
    container_name: hotel-redis
    image: redis:5.0-alpine
    volumes:
      - hotel-redis:/data
    networks:
      - internal

  mailer:
    container_name: hotel-mailer
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8082:8025"
    networks:
      - internal

volumes:
  hotel-postgres:
  hotel-redis:

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.110.0/28