doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'

    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '5.7'

    types:
      user_user_id: 'App\Model\User\Domain\User\DoctrineType\IdType'
      user_user_email: 'App\Model\User\Domain\User\DoctrineType\EmailType'
      user_user_status: 'App\Model\User\Domain\User\DoctrineType\StatusType'
      user_user_role: 'App\Model\User\Domain\User\DoctrineType\RoleType'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      User:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Model/User/Domain'
        prefix: 'App\Model\User\Domain\User'
        alias: User
